apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio
spec:
  selector:
    matchLabels:
      app: socketio
  template:
    metadata:
      labels:
        app: socketio
    spec:
      containers:
      - name: socketio
        image: us-east1-docker.pkg.dev/kiwi-devops/socketio-app/socketio
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000