apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socketio
spec:
  rules:
  - host: socketio.morlax.ar
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: socketio
            port: 
              number: 3000
